wildfly/wildfly-naming-client

- src/main/java/org/wildfly/naming/client/NamingProviderFactory.java
- src/main/java/org/wildfly/naming/client/WildFlyRootContext.java
- src/main/java/org/wildfly/naming/client/_private/Messages.java
- src/main/java/org/wildfly/naming/client/remote/AggregateRemoteNamingProvider.java
- src/main/java/org/wildfly/naming/client/remote/RemoteClientTransport.java
- src/main/java/org/wildfly/naming/client/remote/RemoteNamingProvider.java
- src/main/java/org/wildfly/naming/client/remote/RemoteNamingProviderFactory.java
- src/main/java/org/wildfly/naming/client/remote/SingleRemoteNamingProvider.java
https://issues.jboss.org/browse/WFNC-14
> [WFNC-14] Allow multiple provider URLs to be given

- src/main/java/org/wildfly/naming/client/WildFlyRootContext.java
WildFlyRootContext extended to extend DirContext.
https://issues.jboss.org/browse/WFNC-35
> [WFNC-35] WildFlyRootContext extends DirContext

- src/main/java/org/wildfly/naming/client/ProviderEnvironment.java
https://issues.jboss.org/browse/WFNC-43
https://issues.jboss.org/browse/JBEAP-13214
> [WFNC-43] Ensure a username specified in the InitialContext environment properties actually gets used and no longer set the userInfo for provider URLs

- src/main/java/org/wildfly/naming/client/ProviderEnvironment.java
Small follow-up fix for WFNC-43.
> [WFNC-43] Also add a check to see if a username was specified when determining if the authentication configuration should be overridden

- src/main/java/org/wildfly/naming/client/_private/Messages.java
...since we have been recently counting every wasted byte.
> Comment out unused log messages

- src/main/java/org/jboss/naming/remote/client/InitialContextFactory.java
- src/main/java/org/wildfly/naming/client/_private/Messages.java
https://issues.jboss.org/browse/WFNC-54
> WFNC-54 add support for legacy jboss-naming-client.properties

- src/main/java/org/wildfly/naming/client/remote/RemoteClientTransport.java
- src/main/java/org/wildfly/naming/client/remote/RemoteServerTransport.java
- src/main/java/org/wildfly/naming/client/remote/TCCLUtils.java
https://issues.jboss.org/browse/WFNC-55
> [WFNC-55] Always set TCCL for naming client remoting invocations.

- src/test/java/org/wildfly/naming/client/remote/TestServer.java
- src/test/java/org/wildfly/naming/client/remote/UnmarshallingFilterTestCase.java
https://issues.redhat.com/browse/WFNC-58
> [WFNC-58] Test unmarshalling filtering with a more realistic filter

- src/main/java/org/wildfly/naming/client/NamingProvider.java
- src/main/java/org/wildfly/naming/client/ProviderEnvironment.java
- src/main/java/org/wildfly/naming/client/RetryContext.java
- src/main/java/org/wildfly/naming/client/_private/Messages.java
- src/main/java/org/wildfly/naming/client/remote/RemoteContext.java
- src/test/java/org/wildfly/naming/client/BlocklistTestCase.java
- src/test/java/org/wildfly/naming/client/remote/RemoteContextTestCase.java
- src/test/java/org/wildfly/naming/client/remote/TestServer.java
- src/test/java/org/wildfly/naming/client/remote/UnmarshallingFilterTestCase.java
JIRA: https://issues.redhat.com/browse/WFNC-59
Related: https://issues.redhat.com/browse/EAP7-1558
> WFNC-59 Problematic Language usage deprecation and replacement

- pom.xml
- src/main/java/org/wildfly/naming/client/ProviderEnvironment.java
Issue: https://issues.redhat.com/browse/WFNC-65
> WFNC-65 Upgrade wildfly-elytron and wildfly-common to the latest version

- pom.xml
Issue: https://issues.redhat.com/browse/WFNC-64
> WFNC-64 Update project with a dependency on wildfly-elytron to use individual modules

- pom.xml
Issue: https://issues.redhat.com/browse/WFNC-66
> Upgrade wildfly-elytron to the latest version

- .github/workflows/ci.yml
https://issues.redhat.com/browse/WFNC-71
> WFNC-71 Create github action CI job

- .github/workflows/ci.yml
https://issues.redhat.com/browse/WFNC-72
> WFNC-72 github action ci.yml mvn command contains repeating test phase

- .github/workflows/ci.yml
https://issues.redhat.com/browse/WFNC-85
> WFNC-85 Upgrade github actions to avoid github action warnings

- CONTRIBUTING.md
Issue: https://issues.redhat.com/browse/WFNC-81
> WFNC-81 Add CONTRIBUTING.txt/md/adoc file to this project

- CODEOWNERS
Issue: https://issues.redhat.com/browse/WFNC-84
> WFNC-84 Consider adopting a CODEOWNERS file

- .github/workflows/ci-manual.yml
https://issues.redhat.com/browse/WFNC-89
> WFNC-89 Enable manual start of github actions CI workflow [skip ci]

- pom.xml
https://issues.redhat.com/browse/WFNC-90
> WFNC-90 Add JBoss Public Repository Group to project maven settings in pom.xml

- pom.xml
https://issues.redhat.com/browse/WFNC-93
> [WFNC-93] Upgrading Byteman to 4.0.21 (support for JDK21)

- pom.xml
https://issues.redhat.com/browse/WFNC-95
> [WFNC-95] Enabling code coverage
